"""add_model_sharing_and_webhooks

Revision ID: e3725ab8ee77
Revises: 9ce9de73688d
Create Date: 2025-10-31 09:38:26.849750

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e3725ab8ee77"
down_revision: Union[str, None] = "9ce9de73688d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
